---
  - name: Install php7.0
    yum: pkg={{ item }} state=latest
    with_items:
      - mod_ssl
      - php70w
      - php70w-cli
      - php70w-common
      - php70w-devel
      - php70w-gd
      - php70w-mbstring
      - php70w-mysql
      - php70w-pdo
      - php70w-pear
      - php70w-process
      - php70w-xml
    notify: httpd-restart

  - include:  roles/php7/tasks/composer_task.yml composer_path={{ composer_path}}
