---
  - name: Install php7.0
    apt: pkg={{ item }} state=latest force=yes
    with_items:
      - libapache2-mod-php7.0
      - php7.0-cli
      - php7.0-cgi
      - php-pear
      - php7.0-mysql
      - php7.0-curl
      - php7.0-dev
      - php7.0-gd
      - php7.0-mcrypt
      - php7.0-dom
      - php7.0-zip
    notify: apache2-restart

  - name: PHP | PHPDev | Install composer
    shell:
      curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer

  - name: Apache | Enable mod_php7.0
    apache2_module: state=present name=php7.0
    notify: apache2-restart
