---
  - name: Install php5
    apt: pkg={{ item }} state=latest force=yes
    with_items:
      - php5-fpm
      - php5-mysql
      - php5-cli
      - php5-curl
      - php5-gd

  - name: PHP | Install composer
    shell:
      curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f ./composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer

  - name: PHP | Ensure listen.group is set.
    lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='listen.group = www-data' line='listen.group = www-data' state=present
    notify: php5-fpm-restart

  - name: PHP | Ensure listen.owner is set.
    lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='listen.owner = www-data' line='listen.owner = www-data' state=present
    notify: php5-fpm-restart

  - name: PHP | Add vendor/bin to the user's path
    shell: echo 'export PATH="$PATH:/var/www/vendor/bin"' >> ~/.bashrc
