---
- include_vars: "vars/{{env}}.yml"

- name: Apache | Install Apache
  yum: pkg=nginx state=latest

- name: Apache | Check vhosts path exists
  file: dest=/etc/nginx/sites-available state=directory

- name: Apache | Remove default index file
  file: dest=/var/www/index.html state=absent

- name: Apache | Copy vhost files
  template: src="{{hostTemplate}}" dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=666
  notify: 
  - nginx-restart

- name: Apache | Remove default vhost
  file: dest=/etc/nginx/conf.d/welcome.conf state=absent

- name: Apache | Ensure web directory exists
  file: dest="{{docroot}}" state=directory owner="{{ansible_user}}" group="{{ansible_user}}"

- name: Apache | Copy index template
  template: src="templates/index.j2" dest="{{docroot}}/index.php" owner="{{ansible_user}}" group="{{ansible_user}}" mode=755

- name: Apache | Ensure log directory exists
  file: dest=/var/log/nginx state=directory

- name: Apache | Ensure that Apache is running
  service:
      name=nginx
      state=started
