---
- hosts: webservers
  user: vagrant
  sudo: yes

  vars_files:
  - vars/{{env}}_vars.yml

  vars:
    templates_dir: "templates"

  tasks:
    - include: tasks/base.yml
    - include: tasks/environment.yml
    __TASKS__

  handlers:
    - include: handlers/apache.yml
    - include: handlers/mysql.yml
